# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:opentitan_test.bzl", "opentitan_functest")

opentitan_functest(
    name = "example_test",
    srcs = ["example_test.c"],
    deps = [
        "//sw/device/lib/testing/test_framework:ottf_main",
    ],
)
